name: Test

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

env:
  BEA_KEY: ${{ secrets.BEA_KEY }}
  CENSUS_API_KEY: ${{ secrets.CENSUS_API_KEY }}

jobs:
  prep-pg-docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: docker/build-push-action@v1.1.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          path: db
          repository: valorumdata/cmdc-tools-pg
          tags: ${{ github.ref }}
  test:
    runs-on: ubuntu-latest
    needs: [prep-pg-docker]
    services:
      postgres:
        image: valorumdata/cmdc-tools-pg:${{ github.ref }}
        env:
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.7

      - name: Install dependencies
        run: |
          pip install kedro==0.15.8
          kedro install
      - run: black --check ./src
      - name: run tests
        run: pytest src --maxfail=2
        env:
          PG_CONN_STR: "postgresql://postgres:postgres@localhost:5432"
